# spring application name should be the service name
# to be registered in the eureka discovery server
spring:
  application:
    name: config-server
# configuration fro spring cloud config server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajamuthukalai/config.git
          #username:
          #password:
# other configuration
server:
  port: 8888